### ISSUE TITLE
Adopt a two column layout for contributors

### ISSUE THREAD

**Issue by hashd** [Imaginea/imaginea-oss#1]
Given the amount of space available on screen in the current single column vertical listing, maybe we can consider a two column layout.

Maybe a two column timeline layout like http://images.brisbanetimes.com.au/file/2012/03/30/3175065/fblesson-newsfeed.jpg

**Comment by nagarajhubli** [comment]
I was thinking of the same, implemented the 2 column layout for larger viewports
